---
language: generic

addons:
  apt:
    packages:
      - python3-dev
      - python3-pip

env:
  global:
    - THEMIS_HOME=/tmp/vim-themis
    - THEMIS_VIM="${HOME}/local/bin/vim"
    - PROFILE_LOG="${TRAVIS_BUILD_DIR}/build/profile.txt"

before_install:
  - pip3 install --upgrade pip
  - pip3 install --user vim-vint covimerage
  - go get github.com/haya14busa/go-vimlparser/cmd/vimlparser
  - git clone --depth 1 --branch master --single-branch https://github.com/vim/vim.git /tmp/vim
  - cd /tmp/vim
  - ./configure --with-features=huge --enable-fail-if-missing --prefix="${HOME}/local"
  - make -j3 && make install
  - export PATH="${HOME}/local/bin:${PATH}"
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - shopt -s globstar
  - git clone --depth 1 --branch master --single-branch https://github.com/thinca/vim-themis "${THEMIS_HOME}"
  - mkdir -p build
  - rm -f ./build/coverage.xml "${PROFILE_LOG}" ./build/.coverage.covimerage

script:
  - "\"${THEMIS_VIM}\" --version"
  - "\"${THEMIS_HOME}/bin/themis\" --version"
  - "\"${THEMIS_HOME}/bin/themis\""

after_success:
  - vint autoload plugin
  - vimlparser plugin/**/*.vim autoload/**/*.vim > /dev/null
  - covimerage write_coverage "${PROFILE_LOG}" --data-file ./build/.coverage.covimerage
  - coverage xml
  - coverage report
  - bash <(curl -s https://codecov.io/bash)
